### ISSUE TITLE
Problem didChangeDependencies for repeat load state

### ISSUE THREAD

**Issue by sheillendra** [SAGARSURI/Goals#1]
I add logout menu in Goal List 
```
              onTap: () {
                Navigator.pushReplacement(
                  context,
                  MaterialPageRoute(
                    builder: (context) => LoginPage(),
                  ),
                );
              },
```
and get a problem in the second login screen load, and fix with below code
```
 void didChangeDependencies() {
    super.didChangeDependencies();
    if (_bloc == null) {
      _bloc = LoginBlocProvider.of(context);
    }
  }
```
is this right way?

**Comment by SAGARSURI** [comment]
Basically your stream is getting closed and because of that you have to re-initialise the BLoC. It's a quick fix but later you can create an `init()` inside the BLoC and initialise the `Subjects` there. Call that `init()` inside the `didChangeDependencies()`.
